web:
  last_stable_version: 'master'
  protected_access: false
  name: 'Kalkulator skeleton'
  title_smiley: ''
  repository_url: 'git@github.com:jaroslavtyc/drd-plus-frontend-skeleton-web.git'
  menu_position_fixed: false
  show_home_button: true
  cookies_postfix: 'kalkulator.skeleton'
  cookies_ttl: null
  eshop_url: 'https://obchod.altar.cz/'
google:
  analytics_id: 'UA-121206931-1'