web:
  last_stable_version: '1.0'
  name: 'Kalkulator skeleton'
  title_smiley: ''
  repository_url: 'git@github.com:jaroslavtyc/drd-plus-frontend-skeleton-web.git'
  menu_position_fixed: false
  show_home_button: true
  cookies_postfix: 'kalkulator.skeleton'
  cookies_ttl: null
  source_code_url: 'https://github.com/drdplusinfo/drdplus-calculator-skeleton'
google:
  analytics_id: 'UA-121206931-1'