<?php
global $testsConfiguration;
$testsConfiguration = new \DrdPlus\Tests\CalculatorSkeleton\TestsConfiguration('https://kalkulator.skeleton.drdplus.info');
$testsConfiguration->disableHasCustomBodyContent()
    ->setTooShortFailureNames([])
    ->setTooShortSuccessNames([])
    ->disableHasTables()
    ->setSomeExpectedTableIds([])
    ->disableHasNotes()
    ->disableHasExternalAnchorsWithHashes()
    ->disableHasLinksToAltar()
    ->setExpectedWebName('HTML kostra pro DrD+ kalkulátory')
    ->setExpectedPageTitle('HTML kostra pro DrD+ kalkulátory')
    ->disableHasLinksToAltar()
    ->disableHasAuthors()
    ->disableHasProtectedAccess()
    ->disableCanBeBoughtOnEshop()
    ->disableHasCharacterSheet()
    ->disableHasLinksToJournals()
    ->disableHasLinkToSingleJournal()
    ->disableHasTableOfContents()
    ->disableHasHeadings()
    ->setBlockNamesToExpectedContent([])
    ->disableHasLocalLinks()
    ->disableHasNotes()
    ->setExpectedGoogleAnalyticsId('UA-121206931-1')
    ->setExpectedLicence(\DrdPlus\Tests\RulesSkeleton\TestsConfiguration::LICENCE_MIT);
